# Generated by Django 4.2.4 on 2023-09-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Products',
            new_name='Inventory',
        ),
    ]
